[package]
name = "reks"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { git = "https://github.com/zesterer/chumsky"}
clap = "4.5.31"
inkwell = { version = "0.5.0", features = ["llvm17-0"] }
logos = "0.14.2"
